#!/usr/bin/env bash
[[ " help nginx-path-vhosts:help " == *" $1 "* ]] || [[ "$1" == "${PROXY_NAME}:"* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$_DIR/help-functions"
source "$_DIR/command-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | nginx-path-vhosts:help)
    cmd-nginx-path-vhosts-vhosts-help "$@"
    ;;

  nginx-path-vhosts:access-logs)
    source "$_DIR/subcommands/access-logs"
    ;;

  nginx-path-vhosts:error-logs)
    source "$_DIR/subcommands/error-logs"
    ;;

  nginx-path-vhosts:report)
    cmd-nginx-path-vhosts-report "$@"
    ;;

  nginx-path-vhosts:show-config)
    cmd-nginx-path-vhosts-show-config "$@"
    ;;

  nginx-path-vhosts:validate-config)
    cmd-nginx-path-vhosts-validate-config "$@"
    ;;

  nginx-path-vhosts:set)
    source "$_DIR/subcommands/set"
    ;;

  nginx-path-vhosts:get)
    source "$_DIR/subcommands/get"
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
