#!/usr/bin/env bash
[[ " help nginx-botika:help " == *" $1 "* ]] || [[ "$1" == "${PROXY_NAME}:"* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$_DIR/help-functions"
source "$_DIR/command-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | nginx-botika:help)
    cmd-nginx-botika-vhosts-help "$@"
    ;;

  nginx-botika:access-logs)
    source "$_DIR/subcommands/access-logs"
    ;;

  nginx-botika:error-logs)
    source "$_DIR/subcommands/error-logs"
    ;;

  nginx-botika:report)
    cmd-nginx-botika-report "$@"
    ;;

  nginx-botika:show-config)
    cmd-nginx-botika-show-config "$@"
    ;;

  nginx-botika:validate-config)
    cmd-nginx-botika-validate-config "$@"
    ;;

  nginx-botika:set)
    source "$_DIR/subcommands/set"
    ;;

  nginx-botika:get)
    source "$_DIR/subcommands/get"
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
