#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-nginx-botika-vhosts-help() {
  declare desc="help command"
  declare CMD="$1"
  local plugin_name="${PROXY_NAME}"
  local plugin_description="Manage the nginx proxy"

  if [[ "$CMD" == "${plugin_name}:help" ]]; then
    echo -e "Usage: dokku ${plugin_name}[:COMMAND]"
    echo ''
    echo "$plugin_description"
    echo ''
    echo 'Additional commands:'
    fn-help-content | sort | column -c2 -t -s,
  elif [[ $(ps -o command= $PPID) == *"--all"* ]]; then
    fn-help-content
  else
    cat <<help_desc
    $plugin_name, $plugin_description
help_desc
  fi
}

fn-help-content() {
  declare desc="return help content"
  cat <<help_content
    nginx-botika:access-logs <app> [-t], Show the nginx access logs for an application (-t follows)
    nginx-botika:error-logs <app> [-t], Show the nginx error logs for an application (-t follows)
    nginx-botika:report [<app>] [<flag>], Displays an nginx report for one or more apps
    nginx-botika:set <app> <property> (<value>), Set or clear an nginx property for an app
    nginx-botika:get <app> <property>, Get an nginx property for an app
    nginx-botika:show-config <app>, Display app nginx config
    nginx-botika:start, Starts the nginx server
    nginx-botika:stop, Stops the nginx server
    nginx-botika:validate-config [<app>] [--clean], Validates and optionally cleans up invalid nginx configurations
help_content
}
