#!/usr/bin/env bash
_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$_DIR/config"
source "$_DIR/internal-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

fn-nginx-custom-copy-from-image() {
  declare APP="$1" IMAGE_NAME="$2" CONFIG_FILE_PATH="$3"

  conf_dest_path_base_dir="${DATA_DIRECTORY}/app-$APP/$(dirname ${CONFIG_FILE_PATH})"
  
  mkdir -p "$conf_dest_path_base_dir"

  conf_dest_path_filename_prefix="nginx-custom-config.yaml"
  conf_dest_path_with_pid="$conf_dest_path_base_dir/$conf_dest_path_filename_prefix.$DOKKU_PID"
  conf_dest_missing_path="$conf_dest_path_with_pid.missing"

  find "$conf_dest_path_base_dir" -maxdepth 1 -type f -name "$conf_dest_path_filename_prefix.*" -delete
  copy_from_image "$IMAGE_NAME" "$CONFIG_FILE_PATH" "$conf_dest_path_with_pid" 2>/dev/null || true

  if [[ ! -f "$conf_dest_path_with_pid" ]]; then
    return
  fi
}

trigger-nginx-custom-post-extract() {
  declare desc="${PROXY_NAME} post-extract plugin trigger"
  declare trigger="post-extract"
  declare APP="$1" SOURCECODE_WORK_DIR="$2"
  local app_source_image

  app_source_image="$(plugn trigger git-get-property "$APP" "source-image")"

  config_file_path=$(fn-nginx-custom-config-file "$APP")
  fn-nginx-custom-copy-from-image "$APP" "$app_source_image" "$config_file_path"
}

trigger-nginx-custom-post-extract "$@"
