# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 sw=2 tw=0 et :

vmname = File.basename(File.expand_path(File.dirname(__FILE__)))

Vagrant.configure("2") do |config|
  config.vm.define "Ubuntu-24.04" do |ap|
    ap.vm.box = "bento/ubuntu-24.04"
    ap.vm.hostname = "Ubuntu-24.04"
    
    ap.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--memory", 4096]
    end

    ap.vm.network :private_network, ip: "192.168.56.8"
    ap.vm.network :forwarded_port, guest: 8822, host: 8823
  end

end